question_data = [{"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "The two atomic bombs dropped on Japan by the United States in August 1945 were named "
                              "Little Man and Fat Boy.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "hard",
                  "question": "Joseph Stalin's real name was Ioseb Bessarionis dze Dzugashvili.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Assyrian king Sennacherib's destruction of Babylon in 689 BCE was viewed as a triumph "
                              "by other Assyrian citizens.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "hard",
                  "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more "
                              "powerful and symmetrical.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "United States President Ronald Reagan was the first president to appoint a woman to "
                              "the Supreme Court. ",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "The Hundred Years' War was fought for more than a hundred years.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "easy",
                  "question": "In World War ll, Great Britain used inflatable tanks on the ports of Great Britain to "
                              "divert Hitler away from Normandy D-day landing.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History",
                  "type": "boolean",
                  "difficulty": "medium",
                  "question": "Sir Issac Newton served as a Member of Parliament, but the only recorded time he spoke "
                              "was to complain about a draft in the chambers.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
